require('user.options')
require('user.keymaps')
require('user.plugins')
require('user.colorscheme')
require('user.completion')
require('user.lsp')
require('user.telescope')
require('user.gitsigns')
require('user.treesitter')
require('user.lualine')
require('user.cscope_maps')
require('user.portal')
require'nvim-tree'.setup {}
